(()=>{'use strict';
const $=s=>document.querySelector(s), stage=$('#stage'), head=$('#head'), arm=$('#rightArm'), mouth=$('#mouth'),eyes=[$('#eyeL'),$('#eyeR')];
const expressions={
 idle:{l:'M181 162q18-9 37 0v17q-18 11-37 0z',r:'M279 162q18-9 37 0v17q-18 11-37 0z',bl:'M182 150q17-6 34-1',br:'M280 150q17-6 34-1',m:'M235 194q14 10 28 0'},
 listening:{l:'M181 155q18-5 37 0v25q-18 10-37 0z',r:'M279 155q18-5 37 0v25q-18 10-37 0z',bl:'M181 145l35-4',br:'M280 142l34 3',m:'M239 197q10 3 20 0'},
 curious:{l:'M181 154q18-8 37 0v28q-18 7-37 0z',r:'M279 165q18-9 37-5v17q-18 9-37 0z',bl:'M179 142q17-9 37 0',br:'M280 152l34-6',m:'M239 199q12-6 22-4'},
 skeptical:{l:'M181 169l37-5v13q-18 9-37 0z',r:'M279 155q18-8 37 0v24q-18 10-37 0z',bl:'M181 155l37 7',br:'M280 142q17-10 34-3',m:'M238 201l24-4'},
 amused:{l:'M181 174q18-27 37 0l-3 4q-16-15-31 0z',r:'M279 174q18-27 37 0l-3 4q-16-15-31 0z',bl:'M181 145q17-5 35 1',br:'M280 147q17-5 34-1',m:'M231 191q18 29 37 0z'},
 puzzled:{l:'M181 165q18-14 37-7v19q-18 9-37 0z',r:'M279 158q18-7 37 7v12q-18 9-37 0z',bl:'M181 149l35 5',br:'M280 153l34-8',m:'M235 201q7-7 14-2t14-3'},
 surprised:{l:'M182 161a18 20 0 1 0 36 0a18 20 0 1 0-36 0',r:'M279 161a18 20 0 1 0 36 0a18 20 0 1 0-36 0',bl:'M181 132q18-8 36 0',br:'M279 132q18-8 36 0',m:'M241 198a8 10 0 1 0 16 0a8 10 0 1 0-16 0'},
 waiting:{l:'M181 165l37 3v11q-18 8-37 0z',r:'M279 168l37-3v14q-18 8-37 0z',bl:'M181 152l35 2',br:'M280 154l34-3',m:'M239 200h20'},
 done:{l:'M181 172q18-20 37 0l-3 5q-16-12-31 0z',r:'M279 172q18-20 37 0l-3 5q-16-12-31 0z',bl:'M181 149q18-9 36-1',br:'M279 149q18-9 36-1',m:'M232 194q18 15 36-2'}
};
function face(mode){const f=expressions[mode==='interrupted'?'listening':mode]||expressions.idle;eyes.forEach((e,i)=>{e.style.transform='';e.setAttribute('d',i?f.r:f.l);});mouth.setAttribute('d',f.m);$('#browL').setAttribute('d',f.bl);$('#browR').setAttribute('d',f.br);$('#cheeks').setAttribute('opacity',['amused','done'].includes(mode)?'.8':'0');}

let ctx, analyser, outputGain, naturalGain, circuitGain, media, capture, micSource, silentGain;
let ready=false, live=false, starting=false, capturing=false, manual=false, chunks=[], preroll=[], voiced=0, lastVoice=0, sampleCount=0, above=0;
let sourceContext=[], history=[], active=null, pose='idle', motion=0, epoch=0;
const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');$('#reduce').checked=reducedQuery.matches;
function setPose(mode,status){pose=mode;stage.dataset.state=mode;head.style.transform='';arm.style.transform='';face(mode);if(status)$('#statusText').textContent=status;}
function say(text,speaker='Milo'){$('#caption').textContent=text;$('#speaker').textContent=speaker;}
function note(text){$('#notice').textContent=text;}
function showMetrics(extra={}){$('#metrics').textContent=JSON.stringify({model:$('#model').value,speech:'Pocket TTS · CPU · '+$('#voice').value,voice_sound:$('#voiceColor').value,audio_context:ctx?.state||'not started',microphone:live?'on':'off',...extra},null,2);}
async function health(){try{const r=await fetch('/api/health');const h=await r.json();applySilenceGate(h);ready=h.ready;$('#start').disabled=!ready;$('#send').disabled=!ready;$('#searchWeb').disabled=!ready;$('#audition').disabled=!ready;if(h.error){say('The local speech model could not start. Check the Milo server.');setPose('puzzled','Speech unavailable');}else if(ready){say('What are we figuring out?');setPose('idle','Ready · microphone off');showMetrics();}else setTimeout(health,1500);}catch{say('The local server is unavailable. Start Milo, then reload this page.');setPose('puzzled','Disconnected');}}
// L5A: the server sets the end-of-turn silence gate (350 ms default); the slider still overrides it per session.
function applySilenceGate(h){if(!Number.isFinite(h.silence_ms)||$('#silence').dataset.fromServer)return;$('#silence').value=h.silence_ms;$('#silence').dataset.fromServer='1';$('#silenceLabel').textContent=$('#silence').value+' ms';}
function voiceColor(){if(!naturalGain)return;const natural=$('#voiceColor').value==='natural';naturalGain.gain.setTargetAtTime(natural?1:0,ctx.currentTime,.02);circuitGain.gain.setTargetAtTime(natural?0:1,ctx.currentTime,.02);}
async function audio(){
 if(!ctx){
  ctx=new AudioContext();analyser=ctx.createAnalyser();analyser.fftSize=256;
  outputGain=ctx.createGain();naturalGain=ctx.createGain();circuitGain=ctx.createGain();
  const high=ctx.createBiquadFilter(),low=ctx.createBiquadFilter();high.type='highpass';high.frequency.value=110;low.type='lowpass';low.frequency.value=5200;
  outputGain.connect(naturalGain);naturalGain.connect(analyser);
  outputGain.connect(high);high.connect(low);low.connect(circuitGain);circuitGain.connect(analyser);analyser.connect(ctx.destination);voiceColor();
 }
 if(ctx.state!=='running')await ctx.resume();
}

function animate(){cancelAnimationFrame(motion);if(!active||!active.sources.size||$('#reduce').checked)return;const samples=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(samples);let sum=0;for(const x of samples)sum+=x*x;const amplitude=Math.min(1,Math.sqrt(sum/samples.length)*7);const t=ctx.currentTime,energy=$('#energy').value==='lively'?1.5:.6;if(amplitude>.025){if(pose!=='speaking')setPose('speaking','Speaking');mouth.setAttribute('d',`M235 194q14 ${4+amplitude*26} 28 0q-14 ${-amplitude*8} -28 0`);head.style.transform=`rotate(${2+Math.sin(t*2.8)*energy}deg)`;arm.style.transform=`rotate(${-18+Math.sin(t*2)*7*energy}deg)`;}else mouth.setAttribute('d','M239 197h20');motion=requestAnimationFrame(animate);}
function heard(turn){for(const sentence of turn.sentences.values())if(sentence.ended&&sentence.hasAudio&&sentence.endAt<=ctx.currentTime+.005)sentence.heard=true;}
function storeReply(turn,interrupted){if(turn.audition)return;heard(turn);const text=[...turn.sentences.values()].filter(s=>s.heard).map(s=>s.text).join(' ');if(text)history.push({role:'assistant',content:text+(interrupted?' [User interrupted after this.]':'')});history=history.slice(-12);}
function stopReply(interrupted=true){const old=active;active=null;epoch++;cancelAnimationFrame(motion);if(old){old.abort.abort();fetch('/api/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:old.id}),keepalive:true}).catch(()=>{});storeReply(old,interrupted);for(const source of old.sources){source.onended=null;try{source.stop();}catch{}source.disconnect();}old.sources.clear();for(const timer of old.timers)clearTimeout(timer);old.timers.clear();}$('#stop').disabled=true;setPose(live?'listening':'idle',live?'Listening':'Ready · microphone off');return old;}
function finishReply(turn){if(active!==turn||!turn.done||turn.sources.size)return;storeReply(turn,false);active=null;cancelAnimationFrame(motion);$('#stop').disabled=true;setPose(live?'listening':'idle',live?'Listening':'Ready · microphone off');}
function queueAudio(turn,event){if(active!==turn)return;const binary=atob(event.pcm),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const view=new DataView(bytes.buffer),floats=new Float32Array(bytes.length/4);for(let i=0;i<floats.length;i++)floats[i]=view.getFloat32(i*4,true);const buffer=ctx.createBuffer(1,floats.length,event.sample_rate);buffer.copyToChannel(floats,0);const source=ctx.createBufferSource();source.buffer=buffer;source.connect(outputGain);const startAt=Math.max(ctx.currentTime+.025,turn.nextAt);turn.nextAt=startAt+buffer.duration;const sentence=turn.sentences.get(event.index);sentence.endAt=turn.nextAt;sentence.hasAudio=true;turn.sources.add(source);source.onended=()=>{source.disconnect();turn.sources.delete(source);if(active!==turn)return;heard(turn);finishReply(turn);};source.start(startAt);let peak=0;for(const sample of floats)peak=Math.max(peak,Math.abs(sample));turn.metrics.audio_peak=Math.max(turn.metrics.audio_peak||0,Number(peak.toFixed(4)));if(!turn.metrics.first_playback_ms){turn.metrics.first_playback_ms=Math.round(performance.now()-turn.started+(startAt-ctx.currentTime)*1000);turn.metrics.playback_note='Scheduled Web Audio start relative to request; excludes speaker hardware delay.';showMetrics(turn.metrics);}if(!sentence.captionQueued){sentence.captionQueued=true;const timer=setTimeout(()=>{turn.timers.delete(timer);if(active===turn)say(sentence.text);},Math.max(0,(startAt-ctx.currentTime)*1000));turn.timers.add(timer);}setPose('speaking','Speaking');animate();}
async function sendTurn(input){if(!ready)return;stopReply();const requestEpoch=epoch;await audio();if(epoch!==requestEpoch)return;const turn={id:crypto.randomUUID(),abort:new AbortController(),sources:new Set(),timers:new Set(),sentences:new Map(),audition:!!input.audition,started:performance.now(),nextAt:ctx.currentTime,done:false,metrics:{}};active=turn;$('#stop').disabled=false;setPose('waiting',input.audition?'Preparing voice…':input.audio?'Transcribing locally…':'Thinking locally…');say(input.audio?'One moment…':'…');try{const response=await fetch('/api/turn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:turn.id,messages:input.audition?[]:history,sources:input.audition?[]:sourceContext,model:$('#model').value,voice:$('#voice').value,...input}),signal:turn.abort.signal});if(!response.ok){const e=await response.json();throw Error(e.error||'Local speech unavailable.');}const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const {done,value}=await reader.read();if(active!==turn){reader.cancel();return;}if(done)break;pending+=decoder.decode(value,{stream:true});let nl;while((nl=pending.indexOf('\n'))>=0){const line=pending.slice(0,nl);pending=pending.slice(nl+1);if(!line)continue;const event=JSON.parse(line);if(active!==turn||event.id!==turn.id)return;if(event.type==='transcript'){history.push({role:'user',content:event.text});history=history.slice(-12);$('#transcript').textContent='You: '+event.text;setPose('waiting','Thinking locally…');}else if(event.type==='searching'){setPose('curious','Looking it up…');say('Searching for “'+event.query+'”…');sourceContext=[];renderSources([],event.query);}else if(event.type==='search_failed'){sourceContext=[];renderSources([]);note(event.message);turn.metrics.search_failed=true;}else if(event.type==='sources'){sourceContext=event.sources;renderSources(sourceContext,event.query);setPose('waiting','Reading search snippets…');}else if(event.type==='sentence'){turn.sentences.set(event.index,{text:event.text,endAt:Infinity,ended:false,heard:false,hasAudio:false});}else if(event.type==='audio'){queueAudio(turn,event);}else if(event.type==='sentence_end'){turn.sentences.get(event.index).ended=true;heard(turn);}else if(event.type==='done'){turn.done=true;Object.assign(turn.metrics,event.metrics);showMetrics(turn.metrics);finishReply(turn);}else if(event.type==='error'){throw Error(event.message);}}}if(active===turn&&!turn.done)throw Error('The local reply ended early. Please try again.');}catch(e){if(e.name==='AbortError'||active!==turn)return;stopReply();setPose('puzzled',live?'Listening · last reply failed':'Reply failed');say(e.message);}}
function wavBase64(parts,rate){const length=parts.reduce((n,a)=>n+a.length,0),joined=new Float32Array(length);let at=0;for(const p of parts){joined.set(p,at);at+=p.length;}const ratio=rate/16000,count=Math.floor(length/ratio),data=new ArrayBuffer(44+count*2),v=new DataView(data);const str=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,36+count*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,count*2,true);for(let i=0;i<count;i++){const lo=Math.floor(i*ratio),hi=Math.max(lo+1,Math.floor((i+1)*ratio));let sum=0;for(let j=lo;j<Math.min(hi,length);j++)sum+=joined[j];const x=Math.max(-1,Math.min(1,sum/(Math.min(hi,length)-lo)));v.setInt16(44+i*2,x<0?x*32768:x*32767,true);}let binary='';const bytes=new Uint8Array(data);for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);}
function resetCapture(){capturing=false;chunks=[];sampleCount=0;voiced=0;above=0;preroll=[];}
function beginCapture(isManual=false){stopReply();capturing=true;manual=isManual;chunks=isManual?[]:[...preroll];sampleCount=chunks.reduce((n,a)=>n+a.length,0);voiced=isManual?200:above;lastVoice=performance.now();preroll=[];above=0;setPose('listening','Listening to you');say('Go ahead.','Listening');}
function endCapture(){const parts=chunks,valid=sampleCount>=ctx.sampleRate*.18&&voiced>=160;manual=false;resetCapture();if(valid)sendTurn({audio:wavBase64(parts,ctx.sampleRate)});else setPose('listening','Listening');}
function onMic(event){if(!live)return;const pcm=event.data,ms=pcm.length/ctx.sampleRate*1000;let sum=0;for(const s of pcm)sum+=s*s;const rms=Math.sqrt(sum/pcm.length);$('#level').style.width=Math.min(100,rms*900)+'%';const loud=rms>Number($('#sensitivity').value);if(!capturing){if(!$('#handsfree').checked)return;preroll.push(pcm);while(preroll.length>Math.ceil(ctx.sampleRate*.25/pcm.length))preroll.shift();above=loud?above+ms:0;if(above>=120)beginCapture();return;}chunks.push(pcm);sampleCount+=pcm.length;if(loud){voiced+=ms;lastVoice=performance.now();}if(sampleCount>=ctx.sampleRate*29){endCapture();return;}if(!manual&&performance.now()-lastVoice>=Number($('#silence').value))endCapture();}
async function startMic(){if(starting)return;if(live){endMic();return;}starting=true;$('#start').disabled=true;try{await audio();await ctx.audioWorklet.addModule('/capture.js');media=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(document.hidden){media.getTracks().forEach(t=>t.stop());throw Error('Keep Milo visible to use the microphone.');}micSource=ctx.createMediaStreamSource(media);capture=new AudioWorkletNode(ctx,'milo-capture');silentGain=ctx.createGain();silentGain.gain.value=0;micSource.connect(capture);capture.connect(silentGain);silentGain.connect(ctx.destination);capture.port.onmessage=onMic;live=true;resetCapture();$('#start').textContent='End conversation';$('#ptt').disabled=false;setPose('listening','Listening');say('I’m listening.');note('Microphone on. Voice stays local. Say “look up…” for a web search; only the query goes to search providers.');}catch(e){endMic();say(e.name==='NotAllowedError'?'Microphone permission was not granted. You can still type below.':'Could not open the microphone: '+e.message);}finally{starting=false;$('#start').disabled=!ready;}}
function endMic(){live=false;manual=false;resetCapture();stopReply();if(media)media.getTracks().forEach(t=>t.stop());media=null;if(capture){capture.port.onmessage=null;capture.disconnect();}if(micSource)micSource.disconnect();if(silentGain)silentGain.disconnect();capture=micSource=silentGain=null;$('#start').textContent='Start conversation';$('#ptt').disabled=true;$('#level').style.width='0%';note('Microphone off. Conversation stays in this tab. Web lookup sends only your search query to external search providers.');setPose('idle','Ready · microphone off');say('Microphone off. You can still type.');showMetrics();}
$('#start').onclick=startMic;$('#stop').onclick=()=>{stopReply();say(live?'Go ahead.':'Stopped.');};$('#textForm').onsubmit=e=>{e.preventDefault();const text=$('#text').value.trim();if(text){$('#text').value='';manual=false;resetCapture();sendTurn({text,web:e.submitter?.id==='searchWeb'});}};$('#clear').onclick=()=>{stopReply();history=[];sourceContext=[];renderSources([]);$('#transcript').textContent='';say('A fresh conversation.');};$('#handsfree').onchange=()=>{manual=false;resetCapture();};$('#ptt').onpointerdown=e=>{if(!live)return;e.preventDefault();$('#ptt').setPointerCapture(e.pointerId);beginCapture(true);};$('#ptt').onpointerup=()=>{if(manual)endCapture();};$('#ptt').onpointercancel=()=>{manual=false;resetCapture();setPose('listening','Listening');};window.addEventListener('keydown',e=>{if(e.code==='Escape'){manual=false;resetCapture();stopReply();}if(e.code==='Space'&&!e.repeat&&live&&!/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)){e.preventDefault();beginCapture(true);}});window.addEventListener('keyup',e=>{if(e.code==='Space'&&manual){e.preventDefault();endCapture();}});window.addEventListener('pagehide',endMic);document.addEventListener('visibilitychange',()=>{if(document.hidden)endMic();});
function drawer(open){$('#drawer').hidden=!open;$('#settings').setAttribute('aria-expanded',String(open));if(open)$('#close').focus();else $('#settings').focus();}$('#settings').onclick=()=>drawer($('#drawer').hidden);$('#close').onclick=()=>drawer(false);$('#theme').onchange=e=>document.documentElement.dataset.theme=e.target.value;$('#hands').onchange=e=>stage.classList.toggle('mitts',e.target.value==='mitten');$('#reduce').onchange=()=>{stage.classList.toggle('reduced',$('#reduce').checked);setPose(pose);if($('#reduce').checked)cancelAnimationFrame(motion);else animate();};$('#silence').oninput=e=>$('#silenceLabel').textContent=e.target.value+' ms';$('#sensitivity').oninput=e=>$('#sensitivityLabel').textContent=Number(e.target.value).toFixed(3);document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{stage.dataset.build=b.dataset.build;document.querySelectorAll('[data-build]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#housing').setAttribute('d',b.dataset.build==='box'?'M132 107h211l24 22v101l-20 15H128V124z':'M139 108q101-22 207 3l19 116q-110 39-239 10z');$('#aerial').style.transform=b.dataset.build==='box'?'translate(170px,40px) scale(.7)':'';$('#screenShape').setAttribute('d',b.dataset.build==='box'?'M155 130h181l10 84H155z':'M159 133q89-15 175 0l13 79q-92 22-193 0z');});
function renderSources(sources,query=''){
 $('#sourcesList').replaceChildren();$('#sourcesPanel').hidden=!sources.length;
 $('#sourceLabel').textContent=(sources[0]&&sources[0].origin==='library'?'Offline library results':'Web results')+(query?' · '+query:'');
 for(const source of sources){const li=document.createElement('li'),link=document.createElement('a');link.textContent=source.title;link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';const domain=document.createElement('small');domain.textContent=' · '+(source.origin==='library'?'offline library'+(source.book?' · '+source.book:''):new URL(source.url).hostname);li.append(link,domain);$('#sourcesList').append(li);}
}
for(const id of ['voice','voiceColor','model']){
 const element=$('#'+id);try{const saved=localStorage.getItem('milo-'+id);if([...element.options].some(x=>x.value===saved))element.value=saved;}catch{}
 element.onchange=()=>{if(id==='voiceColor')voiceColor();else stopReply();try{localStorage.setItem('milo-'+id,element.value);}catch{}showMetrics();};
}
$('#clearSources').onclick=()=>{sourceContext=[];renderSources([]);};
$('#audition').onclick=()=>{manual=false;resetCapture();sendTurn({audition:true});};
health();
})();
