import {VOICE_PRESETS} from '/voice-catalog.js';
import {MiloClient} from '/demo-client.js';
import {mountModelLab} from '/model-lab.js';
import {mountVoiceLab} from '/voice-lab.js';
import {mountFileTransfer} from '/file-transfer.js';
import {syncPreferences} from '/preferences.js';
let fileTransfer;
let voiceLab;
const $=selector=>document.querySelector(selector);let selected=null,liveCaption=null,draftProposal=null,draftSeen=null;
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const value=await response.json();if(!response.ok)throw Error(value.error||'The request failed.');return value;}
function message(text,kind=''){const line=document.createElement('p');line.className=kind;line.textContent=text;$('#conversationLog').append(line);$('#conversationLog').scrollTop=$('#conversationLog').scrollHeight;return line;}
function setState(text){$('#benchState').textContent=text;}
const client=new MiloClient(event=>{
 voiceLab?.handleEvent(event);
 if(event.type==='context_summary'){const doc=event.document,parts=[];if(doc)parts.push(doc.characters?'Using '+(doc.truncated?'part of ':'')+doc.name+'.':doc.name+' did not fit in this answer’s context.');if(event.history_omitted||event.sources_omitted)parts.push('Some earlier conversation or search results were left out.');if(parts.length)message(parts.join(' '),'result');}
 if(event.type==='working'){liveCaption=null;setState('Working…');}
 if(event.type==='transcript')message(event.text,'user');
 if(event.type==='route'){$('#deliveryLabel').textContent=event.plan.delivery==='silent'?'Silent · visual acknowledgement':'Spoken answer';}
 if(event.type==='caption'){if(!liveCaption)liveCaption=message(event.text);else liveCaption.textContent=event.text;}
 if(event.type==='speaking'){setState('Speaking');$('#benchRobot').style.transform=`rotate(${Math.min(5,(event.peak??.15)*20)}deg)`;}
 if(event.type==='drafting')setState('Drafting locally…');
 if(event.type==='draft')showDraft(event.proposal);
 if(event.type==='listening')setState('Listening while you hold');
 if(event.type==='searching')setState('Looking it up…');
 if(event.type==='sources'){const box=$('#benchSources');box.replaceChildren();for(const source of event.sources){const link=document.createElement('a');link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=source.title;box.append(link);}}
 if(event.type==='action'){const result=event.result;message((result.status==='preview'?'Preview only · ':'')+result.title+': '+result.detail,result.status==='failed'?'error':'result');if(result.matches)renderMatches(result.matches);if(result.document){showDocument(result.document);refreshFiles();}setState(result.status==='failed'?'Could not finish':'Done, quietly');$('#benchRobot').animate([{transform:'rotate(0)'},{transform:'rotate(-9deg)'},{transform:'rotate(0)'}],{duration:650});}
 if(event.type==='provider')message('Answer from '+event.provider.model+' · '+event.provider.destination+'. Current question only.','result');
 if(event.type==='api_proposal'){message('Higher-model route proposed. No API request was sent.','result');renderRoute({plan:{kind:'api_preview',delivery:'spoken'},proposal:event.proposal});}
 if(event.type==='error'){setState('Try again');message(event.message,'error');}
 if(event.type==='idle'||event.type==='stopped'){$('#benchRobot').style.transform='';setState(event.type==='stopped'?'Stopped':'Ready');}
});
void mountModelLab($('#modelLab'));
voiceLab=mountVoiceLab($('#voiceLab'),client);
fileTransfer=mountFileTransfer({mount:$('#fileTransfer'),onImport:async({name,content})=>{const result=await api('/api/demo/document',{operation:'create',name,content});showDocument(result.document);await refreshFiles();message('Imported '+name+' into the local notebook.','result');},getCurrentDocument:()=>selected?{name:selected.name,content:$('#documentEditor').value,label:$('#documentEditor').value===selected.content?'saved document':'current editor'}:null});
$('#documentEditor').addEventListener('input',()=>fileTransfer.refresh());
window.addEventListener('milo-preference-change',()=>{$('#demoVoice').value=client.voice;$('#demoMode').value=client.mode;$('#demoModel').value=client.model;});
$('#demoVoice').replaceChildren(...Object.entries(VOICE_PRESETS).map(([id,label])=>new Option(label,id)));
$('#demoVoice').value=client.voice;$('#demoMode').value=client.mode;
const preferenceSync=syncPreferences({client,onUpdated:value=>{voiceLab?.setPreferences(value);$('#demoVoice').value=value.voice;$('#demoMode').value=value.mode;if(value.model)$('#demoModel').value=value.model;}});
window.addEventListener('milo-preferences-error',event=>message('Preferences: '+event.detail.message,'error'));
function tab(name){for(const element of document.querySelectorAll('.tab-panel'))element.hidden=element.id!==name;for(const button of document.querySelectorAll('[data-tab]'))button.setAttribute('aria-selected',String(button.dataset.tab===name));document.querySelector('[data-tab="'+name+'"]')?.scrollIntoView({block:'nearest',inline:'center'});const url=new URL(location.href);url.searchParams.set('tab',name);history.replaceState(null,'',url);if(name==='workbench')refreshFiles();}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
function providerChoice(state){const option=$('#demoBackend option[value=api]');option.disabled=!state.provider?.configured;option.textContent=state.provider?.configured?'API · '+state.provider.model:'API · not configured';$('#connectionStatus').textContent=state.provider?.configured?state.provider.model+' at '+state.provider.destination+'. '+state.provider.sharing:(state.provider?.reason||'Not configured.');}
$('#demoBackend').onchange=()=>{client.stop();client.backend=$('#demoBackend').value;$('#providerNotice').textContent=client.backend==='api'?'API sends this question only. No history, document contents or audio. Provider charges may apply.':'Local model. The selected note can be included.';};
function modelChoice(state){if(!state.models)return;const current=client.model;$('#demoModel').replaceChildren(...Object.entries(state.models).map(([id,label])=>new Option(label,id)));$('#demoModel').value=state.models[current]?current:state.model;}
async function ready(){try{const state=await api('/api/demo/state');providerChoice(state);modelChoice(state);$('#readyText').textContent=state.ready?'Working demos are ready':state.error?'Local speech failed to load. Notebook editing still works.':'Warming up local speech…';$('#readyDot').classList.toggle('ready',state.ready);$('#sendDemo').disabled=$('#holdDemo').disabled=!state.ready;if(!state.ready)setTimeout(ready,1500);}catch{$('#readyText').textContent='Demo server unavailable';}}
async function refreshFiles(){try{const state=await api('/api/demo/state');if(state.draft&&state.draft.id!==draftSeen)showDraft(state.draft);$('#fileList').replaceChildren();for(const doc of state.documents){const button=document.createElement('button');button.textContent=doc.name;button.classList.toggle('selected',doc.name===selected?.name);button.onclick=()=>openDocument(doc.name);$('#fileList').append(button);}if(!selected&&state.documents.length)await openDocument((state.documents.find(doc=>doc.name==='project-brief.md')||state.documents[0]).name);}catch(error){message(error.message,'error');}}
async function openDocument(name){try{showDocument(await api('/api/demo/document?name='+encodeURIComponent(name)));await refreshFiles();}catch(error){message(error.message,'error');}}
function showDocument(doc){selected=doc;client.document=doc.name;$('#documentTitle').textContent=doc.name;$('#documentInfo').textContent=doc.bytes+' bytes · local demo file';$('#documentEditor').disabled=false;$('#documentEditor').value=doc.content;$('#saveDocument').disabled=false;$('#documentReceipt').textContent='';loadRevisions();fileTransfer?.refresh();}
async function loadRevisions(){try{const rows=await api('/api/demo/revisions?name='+encodeURIComponent(selected.name));$('#revisionSelect').replaceChildren(new Option('Earlier versions',''));for(const revision of rows)$('#revisionSelect').add(new Option(revision.revision.slice(0,8)+' · '+revision.bytes+' bytes',revision.revision));$('#restoreDocument').disabled=true;}catch(error){$('#documentReceipt').textContent=error.message;}}
$('#saveDocument').onclick=async()=>{try{const result=await api('/api/demo/document',{operation:'replace',name:selected.name,content:$('#documentEditor').value,revision:selected.revision});showDocument(result.document);$('#documentReceipt').textContent='Saved. Previous version kept.';message('Saved '+selected.name+' without a spoken acknowledgement.','result');refreshFiles();}catch(error){$('#documentReceipt').textContent=error.message;}};
$('#newDocument').onclick=async()=>{const name=prompt('Name for a new demo note (for example, weekend-plan.md)');if(!name)return;try{const result=await api('/api/demo/document',{operation:'create',name,content:'# A new note\n\n'});showDocument(result.document);refreshFiles();}catch(error){message(error.message,'error');}};
$('#revisionSelect').onchange=()=>$('#restoreDocument').disabled=!$('#revisionSelect').value;
$('#restoreDocument').onclick=async()=>{try{const result=await api('/api/demo/document',{operation:'restore',name:selected.name,revision:selected.revision,restore_revision:$('#revisionSelect').value});showDocument(result.document);$('#documentReceipt').textContent='Earlier version restored. Replaced version also kept.';refreshFiles();}catch(error){$('#documentReceipt').textContent=error.message;}};
$('#talkForm').onsubmit=event=>{event.preventDefault();const text=$('#talkInput').value.trim();if(text){$('#talkInput').value='';client.submit(text);}};
for(const button of document.querySelectorAll('[data-example]'))button.onclick=()=>{$('#talkInput').value=button.dataset.example;$('#talkInput').focus();};
$('#demoMode').onchange=()=>{client.mode=$('#demoMode').value;preferenceSync.save({mode:client.mode});};
$('#demoVoice').onchange=()=>{client.voice=$('#demoVoice').value;preferenceSync.save({voice:client.voice});};$('#demoModel').onchange=()=>{client.stop();client.model=$('#demoModel').value;preferenceSync.save({model:client.model});$('#providerNotice').textContent=client.model.startsWith('gemma3-abliterated')?'Unfiltered model: answers without refusals or disclaimers. Loading it swaps the GPU model, so the first answer takes longer.':'Local model. The selected note can be included.';};$('#stopDemo').onclick=()=>{client.cancelRecording();client.stop();};
$('#holdDemo').onpointerdown=event=>{event.preventDefault();$('#holdDemo').setPointerCapture(event.pointerId);client.record();};$('#holdDemo').onpointerup=()=>client.finishRecording();$('#holdDemo').onpointercancel=()=>client.cancelRecording();
function renderRoute(data){const {plan,proposal}=data;$('#routeTitle').textContent=plan.delivery==='silent'?'An action. Keep it quiet.':proposal.suggested?'A candidate for a stronger model.':'A question. Answer locally.';$('#routeReason').textContent=proposal.reason;$('#routePayload').textContent=JSON.stringify(proposal,null,2);const steps=plan.delivery==='silent'?['Recognize the command','Use the command path','Show a small visual acknowledgement']:proposal.suggested?['Recognize the question','Propose a higher-model request','Keep it unsent until provider and sharing choices exist']:['Recognize the question','Use the local model','Speak the answer'];$('#routeSteps').replaceChildren(...steps.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));}
$('#inspectRoute').onclick=async()=>{try{renderRoute(await api('/api/demo/route',{text:$('#routeText').value,document:client.document}));}catch(error){$('#routeReason').textContent=error.message;}};
for(const button of document.querySelectorAll('[data-route-example]'))button.onclick=()=>{$('#routeText').value=button.dataset.routeExample;$('#inspectRoute').click();};
const variants=[['A','Peek','A small bubble above the icon','A quiet popover'],['B','Shelf','A command strip across the bottom','One quick command'],['C','Sidekick','A narrow place for ongoing context','A little room to talk']];let variant=Math.max(0,variants.findIndex(row=>row[0]===new URL(location.href).searchParams.get('variant'))),studyTimer;
function setVariant(index){variant=(index+variants.length)%variants.length;const [key,title,hint,panelTitle]=variants[variant];$('#study').dataset.variant=key;$('#variantLabel').textContent=key+' · '+title;$('#variantHint').textContent=hint;$('#studyTitle').textContent=panelTitle;const url=new URL(location.href);url.searchParams.set('variant',key);history.replaceState(null,'',url);}
$('#previousVariant').onclick=()=>setVariant(variant-1);$('#nextVariant').onclick=()=>setVariant(variant+1);$('#studyRobot').onclick=()=>$('#study').dataset.open=String($('#study').dataset.open!=='true');$('#studyCollapse').onclick=()=>$('#study').dataset.open='false';
async function studyRequest(text){try{const {plan}=await api('/api/demo/route',{text});$('#study').dataset.open='true';$('#study').dataset.state=plan.delivery==='silent'?'done':'speaking';$('#studyDelivery').textContent=plan.delivery==='silent'?'Scripted · silent acknowledgement':'Scripted · spoken answer';$('#studyResponse').textContent=plan.delivery==='silent'?'A small nod, and back to your work. No spoken confirmation.':'The answer appears here while Milo speaks. The working voice demo is in the notebook tab.';$('#studyHistory').textContent='You: '+text;clearTimeout(studyTimer);studyTimer=setTimeout(()=>$('#study').dataset.state='idle',2200);}catch(error){$('#studyResponse').textContent=error.message;}}
for(const button of document.querySelectorAll('[data-study-command]'))button.onclick=()=>studyRequest(button.dataset.studyCommand);
$('#studyForm').onsubmit=event=>{event.preventDefault();studyRequest($('#studyInput').value);};$('#resetStudy').onclick=()=>{$('#study').dataset.open='false';$('#study').dataset.state='idle';$('#studyResponse').textContent='Ask a question, or give me something to do.';$('#studyDelivery').textContent='Ready when you are';};
window.addEventListener('keydown',event=>{if(event.key==='Escape'){client.cancelRecording();client.stop();$('#study').dataset.open='false';}if(!$('#presence').hidden&&!/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();setVariant(variant+(event.key==='ArrowRight'?1:-1));}});
window.addEventListener('pagehide',()=>{client.cancelRecording();client.stop();});document.addEventListener('visibilitychange',()=>{if(document.hidden){client.cancelRecording();client.stop();}});
setVariant(variant);tab(new URL(location.href).searchParams.get('tab')||'presence');ready();refreshFiles();

function renderMatches(matches){const box=$('#noteMatches');box.replaceChildren();if(!matches.length){box.textContent='No matching note text.';return;}for(const match of matches){const button=document.createElement('button');button.textContent=match.name+' · line '+match.line+': '+match.excerpt;button.onclick=()=>openDocument(match.name);box.append(button);}}
$('#noteSearchForm').onsubmit=async event=>{event.preventDefault();const query=$('#noteSearch').value.trim();if(!query){$('#noteMatches').replaceChildren();return;}try{renderMatches(await api('/api/demo/search-documents?q='+encodeURIComponent(query)));}catch(error){message(error.message,'error');}};
let applyingDraft=false;
$('#applyDraft').onclick=async()=>{if(!draftProposal||applyingDraft)return;const proposal=draftProposal;applyingDraft=true;$('#applyDraft').disabled=$('#dismissDraft').disabled=true;$('#draftReceipt').textContent='Saving…';try{const result=await api('/api/demo/document',{operation:proposal.revision?'replace':'create',name:proposal.name,revision:proposal.revision,content:$('#draftText').value,draft_id:proposal.id});showDocument(result.document);refreshFiles();if(draftProposal?.id===proposal.id){$('#draftReceipt').textContent='Saved. Earlier version retained when replacing.';$('#draftReview').hidden=true;$('#showLastDraft').hidden=true;draftProposal=null;}message('Saved draft '+proposal.name+' quietly.','result');}catch(error){if(draftProposal?.id===proposal.id)$('#draftReceipt').textContent=error.message;else message('Could not save '+proposal.name+': '+error.message,'error');}finally{applyingDraft=false;$('#applyDraft').disabled=$('#dismissDraft').disabled=false;}};
$('#dismissDraft').onclick=()=>{if(applyingDraft)return;$('#draftReview').hidden=true;$('#showLastDraft').hidden=false;message('Draft left unsaved. The generated version is shared across Milo windows until another draft or a server restart; your edits here stay in this tab.','result');};

function showDraft(proposal){draftProposal=proposal;draftSeen=proposal.id;$('#draftReview').hidden=false;$('#showLastDraft').hidden=true;$('#draftTitle').textContent='Draft · '+proposal.name;$('#draftText').value=proposal.content;$('#draftReceipt').textContent='';message('Draft ready for review. Nothing saved yet.','result');}
$('#showLastDraft').onclick=()=>{$('#draftReview').hidden=false;$('#showLastDraft').hidden=true;};
