// Own-app browser smoke and layout captures. No microphone permission requested.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1320,height:1000}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const dir=path.join(__dirname,'evidence');fs.mkdirSync(dir,{recursive:true});
for(const variant of ['A','B','C']){await page.goto('http://127.0.0.1:8776/demo?variant='+variant+'&tab=presence');await page.getByRole('button',{name:'Open Firefox',exact:true}).click();await page.locator('#studyResponse').filter({hasText:'A small nod'}).waitFor();await page.locator('#study').screenshot({path:path.join(dir,'presence-'+variant+'.png')});}
await page.getByRole('button',{name:'02 · A working notebook'}).click();await page.locator('#documentEditor').filter({visible:true}).waitFor();await page.locator('#workbench').screenshot({path:path.join(dir,'notebook.png')});
await page.getByRole('button',{name:'03 · Choosing a brain'}).click();await page.locator('.routing-details summary').click();await page.locator('#routeText').fill('Use a stronger model to compare architecture tradeoffs');await page.locator('#inspectRoute').click();await page.locator('#routeTitle').filter({hasText:'candidate'}).waitFor();await page.locator('#routing').screenshot({path:path.join(dir,'routing.png')});
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8776/demo?variant=A&tab=workbench');await page.locator('#documentEditor').waitFor();const horizontalOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(horizontalOverflow)throw Error('Mobile horizontal overflow');await page.screenshot({path:path.join(dir,'mobile.png'),fullPage:true});
await page.setViewportSize({width:400,height:560});await page.goto('http://127.0.0.1:8776/overlay');await page.locator('#robot').click();await page.locator('#text').fill('Open Firefox');await page.locator('#send').click();await page.locator('#reply').filter({hasText:'Preview only'}).waitFor();await page.screenshot({path:path.join(dir,'overlay.png')});await page.locator('#minimize').click();if(await page.locator('body').getAttribute('data-expanded')!=='false')throw Error('Collapse failed');if(errors.length)throw Error(JSON.stringify(errors));fs.writeFileSync(path.join(dir,'browser.json'),JSON.stringify({passed:true,errors,horizontalOverflow,captured:['presence-A','presence-B','presence-C','notebook','routing','mobile','overlay'],microphone_tested:false},null,2));await browser.close();console.log('Browser checks passed');})().catch(error=>{console.error(error);process.exit(1)});
